name: utilsforecast
channels:
  - conda-forge
dependencies:
  - matplotlib
  - nbformat
  - numba
  - numpy
  - pandas
  - plotly
  - pip
  - pyarrow
  - scipy
  - pip:
    - nbdev
    - plotly-resampler
    - polars
