name: utilsforecast
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - nbformat
  - numba
  - numpy
  - pandas
  - plotly
  - pip
  - pyarrow
  - scipy
  - pip:
      - datasetsforecast==0.0.8
      - nbdev
      - plotly-resampler
      - polars
