site_name: utilsforecast
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference:
    - data: api/data.md
    - evaluation: api/evaluation.md
    - feature_engineering: api/feature_engineering.md
    - preprocessing: api/preprocessing.md
    - processing: api/processing.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_source: false