# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/utilsforecast',
                'doc_host': 'https://Nixtla.github.io',
                'git_url': 'https://github.com/Nixtla/utilsforecast',
                'lib_path': 'utilsforecast'},
  'syms': { 'utilsforecast.compat': {},
            'utilsforecast.data': {'utilsforecast.data.generate_series': ('data.html#generate_series', 'utilsforecast/data.py')},
            'utilsforecast.plotting': { 'utilsforecast.plotting._filter_series': ( 'plotting.html#_filter_series',
                                                                                   'utilsforecast/plotting.py'),
                                        'utilsforecast.plotting.plot': ('plotting.html#plot', 'utilsforecast/plotting.py')},
            'utilsforecast.preprocessing': { 'utilsforecast.preprocessing._determine_bound': ( 'preprocessing.html#_determine_bound',
                                                                                               'utilsforecast/preprocessing.py'),
                                             'utilsforecast.preprocessing.fill_gaps': ( 'preprocessing.html#fill_gaps',
                                                                                        'utilsforecast/preprocessing.py')},
            'utilsforecast.validation': { 'utilsforecast.validation.validate_format': ( 'validation.html#validate_format',
                                                                                        'utilsforecast/validation.py')}}}
